In [1]:
import numpy as np
import matplotlib.pyplot as plt

# 6. Matrics

### 6.1 Matrics Basic

In [7]:
A = np.array([[0,1,-2.3,0.1],[1.3, 4, -0.1, 0],[4.1, -1.0, 0, 1.7]])
A.shape

(3, 4)

In [5]:
A = [[0,1,-2.3,0.1],[1.3, 4, -0.1, 0],[4.1, -1.0, 0, 1.7]]
len(A), len(A[0])

(3, 4)

In [8]:
A[0,2]

-2.3

In [9]:
A[1]

array([ 1.3,  4. , -0.1,  0. ])

#### Column, Row vector v.s. 1-D array

In [10]:
# vector
a = np.array([1,4,2])
a.shape

(3,)

In [11]:
# 3 by 1 matrics (column vector)
a = np.array([[1],[4],[2]])
a.shape

(3, 1)

In [12]:
# row vector, 1 by 3 matrics
a= np.array([[1,4,2]])
a.shape

(1, 3)

In [15]:
A[:,1].shape

(3,)

In [16]:
A[0].shape

(4,)

#### slicing

In [17]:
A = np.array([[-1, 0, 1, 0],[2, -3, 0, 1],[0, 4, -2, 1]])

In [18]:
A[0:2, 2:4]

array([[1, 0],
       [0, 1]])

In [19]:
A.shape

(3, 4)

In [20]:
A.reshape(6,2)

array([[-1,  0],
       [ 1,  0],
       [ 2, -3],
       [ 0,  1],
       [ 0,  4],
       [-2,  1]])

#### Block Matrices

In [21]:
B = np.array([0,2,3]) #1 by 3 matrix
C = np.array([-1]) #1 by 1 matrix
D = np.array([[2,2,1],[1,3,5]]) #2 by 3 matrix
E = np.array([[4],[4]]) #2 by 1 matrix

In [22]:
# construct a block 3 by 4 matix
np.block([[B,C], [D,E]])

array([[ 0,  2,  3, -1],
       [ 2,  2,  1,  4],
       [ 1,  3,  5,  4]])

#### Stack vectors into matrix

In [23]:
a = [1,2]
b = [4,5]
c = [7,8]

In [26]:
# stack row vectors
A = np.vstack([a,b,c])
A

array([[1, 2],
       [4, 5],
       [7, 8]])

In [29]:
# stack columns vactors
B = np.hstack([a,b,c])
B

array([1, 2, 4, 5, 7, 8])

In [31]:
C = np.concatenate([a,b,c])
C

array([1, 2, 4, 5, 7, 8])

In [32]:
a = [[1],[2]]
b = [[4],[5]]
c = [[7],[8]]

In [33]:
np.vstack([a,b,c])

array([[1],
       [2],
       [4],
       [5],
       [7],
       [8]])

In [35]:
np.hstack([a,b,c])

array([[1, 4, 7],
       [2, 5, 8]])

In [36]:
np.concatenate([a,b,c])

array([[1],
       [2],
       [4],
       [5],
       [7],
       [8]])

#### stack column/row vector into matrix

In [38]:
np.c_[np.identity(3), np.zeros(3)]

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [40]:
np.r_[np.identity(3), np.ones((1,3))]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 1., 1.]])

### 6.2 Special Matrices

In [41]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [50]:
# random bwteen 0 and 1
np.random.random((2,3))

array([[0.95574109, 0.97301587, 0.59310882],
       [0.35352394, 0.88163689, 0.13953443]])

In [47]:
# random normal
np.random.randn(3,2)

array([[-1.13548355,  0.3617871 ],
       [-0.2671604 , -1.6311187 ],
       [-0.67803647, -1.07637035]])

### 6.3 Transpose

In [51]:
H = np.array([[0,1,-2,1],[2,-1,3,0]])

In [52]:
H.T

array([[ 0,  2],
       [ 1, -1],
       [-2,  3],
       [ 1,  0]])

In [53]:
np.transpose(H)

array([[ 0,  2],
       [ 1, -1],
       [-2,  3],
       [ 1,  0]])

In [54]:
A = np.array([[2,3,-1],[0,-1,4]])
np.linalg.norm(A)

5.5677643628300215

### 6.4 Matrix-Vector mutiplication 
matrix-vector multiplication has the natural syntax y = A @ x. Alternatively,
we can use the numpy function np.matmul(A,x).

In [55]:
A = np.array([[0,2,-1],[-2,1,1]])
x = np.array([2,1,-1])

In [56]:
x.shape

(3,)

In [57]:
A@x

array([ 3, -4])

In [60]:
np.matmul(A,x)

array([ 3, -4])

#### To Do: 
Running sum matrix  
Vandermonde matrix

# 10. Matrix multiplication

### 10.1 Matrix-matrix multiplication 
same as matrix-vector: A@B or np.matmul(A,B)

In [61]:
A = np.array([[-1.5, 3, 2],[1, -1,0]]) #2 by 3 matrix
B = np.array([[-1,-1],[0,-2],[1,0]]) #3 by 2 matrix

In [62]:
A

array([[-1.5,  3. ,  2. ],
       [ 1. , -1. ,  0. ]])

In [63]:
B

array([[-1, -1],
       [ 0, -2],
       [ 1,  0]])

In [64]:
A@B

array([[ 3.5, -4.5],
       [-1. ,  1. ]])

In [65]:
np.matmul(A,B)

array([[ 3.5, -4.5],
       [-1. ,  1. ]])

#### Gram Matrix 
The Gram matrix of a matrix A is the matrix G = ATA. It is a symmetric
matrix and the i; j element Gi;j is the inner product of columns i and j of A.

In [67]:
A.T

array([[-1.5,  1. ],
       [ 3. , -1. ],
       [ 2. ,  0. ]])

In [68]:
A

array([[-1.5,  3. ,  2. ],
       [ 1. , -1. ,  0. ]])

In [70]:
G = A.T @ A
G

array([[ 3.25, -5.5 , -3.  ],
       [-5.5 , 10.  ,  6.  ],
       [-3.  ,  6.  ,  4.  ]])

#### Associative property

In [2]:
m = 100
n = 20
q = 100
p = 100
A = np.random.normal(size=(m,n))
B = np.random.normal(size = (n,p))
C = np.random.normal(size = (p,q))

In [3]:
LHS = A@B@C
RHS = A@(B@C)

In [4]:
np.linalg.norm(LHS-RHS)

2.229764698326084e-12

### 10.2 Compossition for linear functions

#### Second Difference Matrix 
The matrices have constant diagonals. Right away that property wakes up
Fourier. It signifies that something is not changing when we move in space or
time. The problem is shift-invariant or time-invariant. Coefficients are constant.

In [5]:
D = lambda n: np.c_[-np.identity(n-1), np.zeros(n-1)] + np.c_[np.zeros(n-1), np.identity(n-1)]

In [6]:
D(4)

array([[-1.,  1.,  0.,  0.],
       [ 0., -1.,  1.,  0.],
       [ 0.,  0., -1.,  1.]])

In [7]:
D(5)

array([[-1.,  1.,  0.,  0.,  0.],
       [ 0., -1.,  1.,  0.,  0.],
       [ 0.,  0., -1.,  1.,  0.],
       [ 0.,  0.,  0., -1.,  1.]])

### 10.3 Matrix Power

In [9]:
A = np.array([[0,1,0,0,1],[1,0,1,0,0],[0,0,1,1,1],
[1,0,0,0,0],[0,0,0,1,0]])

In [10]:
np.linalg.matrix_power(A,2)

array([[1, 0, 1, 1, 0],
       [0, 1, 1, 1, 2],
       [1, 0, 1, 2, 1],
       [0, 1, 0, 0, 1],
       [1, 0, 0, 0, 0]])

In [11]:
np.linalg.matrix_power(A,8)

array([[18, 11, 15, 20, 20],
       [25, 14, 21, 28, 26],
       [24, 14, 20, 27, 26],
       [11,  6,  9, 12, 11],
       [ 6,  4,  5,  7,  7]])

### 10.4 QR Decomposition

In linear algebra, a QR decomposition, also known as a QR factorization is a decomposition of a matrix A into a product A = QR of an orthogonal matrix Q and an upper triangular matrix R.  
QR decomposition is often used to solve the linear least squares problem and is the basis for a particular eigenvalue algorithm, the QR algorithm.

Any real square matrix A may be decomposed as

$$ A = QR $$

where Q is an orthogonal matrix (its columns are orthogonal unit vectors meaning $$ Q^TQ = I$$ and R is an upper triangular matrix (also called right triangular matrix, hence the name). If A is invertible, then the factorization is unique if we require the diagonal elements of R to be positive.

When we wrote the gram_schmidt function, we try to check if the rows of
the numpy array (matrix A) are linearly independent. However, in QR factorisation, we
should perform the Gram-Schmidt on the columns of matrix A. Therefore, AT should be
the input to the QR_factorization instead of A.

In [23]:
def gram_schmidt(a):
    q = []
    for i in range(len(a)):
        #orthogonalization
        q_tilde = a[i]
        for j in range(len(q)):
            q_tilde = q_tilde - (q[j] @ a[i])*q[j]
            #Test for dependennce
        if np.sqrt(sum(q_tilde**2)) <= 1e-10:
            print("Vectors are linearly dependent.")
            print ("GS algorithm terminates at iteration ", i+1)
            return q
        #Normalization
        else:
            q_tilde = q_tilde / np.sqrt(sum(q_tilde**2))
            q.append(q_tilde)
    print("Vector are linearly independent.")
    return q

In [24]:
a = np.array([ [-1, 1, -1, 1], [-1, 3, -1, 3], [1, 3, 5, 7] ])
q = gram_schmidt(a)
print (q)

Vector are linearly independent.
[array([-0.5,  0.5, -0.5,  0.5]), array([0.5, 0.5, 0.5, 0.5]), array([-0.5, -0.5,  0.5,  0.5])]


In [29]:
def QR_factorization(A):
    Q_transpose = np.array(gram_schmidt(A.T))
    R = Q_transpose @ A
    Q = Q_transpose.T
    return Q, R

In [30]:
A = np.random.normal(size = (6,4))
Q,R = np.linalg.qr(A)

In [31]:
R

array([[ 3.469566  , -1.1979012 ,  1.15753995,  0.40935593],
       [ 0.        , -2.00047269,  0.39211132, -0.09442646],
       [ 0.        ,  0.        ,  1.04525047, -1.41933916],
       [ 0.        ,  0.        ,  0.        , -1.26265251]])

In [32]:
q,r = QR_factorization(A)
r

Vector are linearly independent.


array([[ 3.46956600e+00, -1.19790120e+00,  1.15753995e+00,
         4.09355930e-01],
       [ 9.71445147e-17,  2.00047269e+00, -3.92111321e-01,
         9.44264614e-02],
       [-4.44089210e-16,  1.66533454e-16,  1.04525047e+00,
        -1.41933916e+00],
       [-4.44089210e-16,  2.22044605e-16, -3.98986399e-16,
         1.26265251e+00]])

In [33]:
np.linalg.norm(Q@R - A)

9.035628243514969e-16

In [34]:
Q.T @ Q

array([[ 1.00000000e+00, -9.39743237e-18, -6.26278863e-17,
        -5.94185786e-18],
       [-9.39743237e-18,  1.00000000e+00,  2.69653464e-16,
        -4.23531172e-17],
       [-6.26278863e-17,  2.69653464e-16,  1.00000000e+00,
         3.63343843e-17],
       [-5.94185786e-18, -4.23531172e-17,  3.63343843e-17,
         1.00000000e+00]])

# 11. Matrix Inverse

### 11.2 Inverse

In [35]:
A = np.array([[1,-2,3],[0,2,2],[-4,-4, -4]])

In [36]:
B = np.linalg.inv(A)

In [37]:
B @ A

array([[ 1.00000000e+00, -2.22044605e-16, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00,  8.32667268e-17],
       [ 0.00000000e+00,  5.55111512e-17,  1.00000000e+00]])

#### Inverse via QR factorization 
$$ A^-1 = R^-1 Q^T $$

In [38]:
A = np.random.normal(size=(3,3))
np.linalg.inv(A)

array([[ 0.96222251,  0.04719067, -0.06698984],
       [-0.54853222,  1.27190475, -0.1844015 ],
       [-0.99454521,  0.96037692,  0.35070684]])

In [39]:
Q,R = np.linalg.qr(A)

In [42]:
np.linalg.inv(R) @ Q.T

array([[ 0.96222251,  0.04719067, -0.06698984],
       [-0.54853222,  1.27190475, -0.1844015 ],
       [-0.99454521,  0.96037692,  0.35070684]])

### 11.3 Solving Linear Equations

Using the gram_schmidt, QR_factorization and back_subsitution

In [43]:
def back_subst(R, b_tilde):
    n = R.shape[0]
    x = np.zeros(n)
    
    for i in reversed(range(n)):
        x[i] = b_tilde[i]
        for j in range(i+1, n):
            x[i] = x[i] - R[i,j]*x[j]
        x[i] = x[i]/R[i,i]
    return x

In [44]:
R = np.triu(np.random.random((4,4)))
R

array([[0.05457118, 0.94596039, 0.23911412, 0.75456885],
       [0.        , 0.30824886, 0.68118895, 0.25741646],
       [0.        , 0.        , 0.22434505, 0.9963573 ],
       [0.        , 0.        , 0.        , 0.87563488]])

In [46]:
b = np.random.random(4)

In [48]:
x = back_subst(R, b)

In [50]:
R @ x - b

array([0., 0., 0., 0.])

#### solving system of linear equations

In [51]:
def solve_via_backsub(A,b):
    Q,R = QR_factorization(A)
    b_tilde = Q.T @ b
    x = back_subst(R, b_tilde)
    return x

#### np.linalg.solve(A, b)

In [52]:
n = 50
A = np.random.normal(size=(n,n))
b = np.random.normal(size=n)

In [53]:
x1 = solve_via_backsub(A,b)

Vector are linearly independent.


In [55]:
x2 = np.linalg.solve(A, b)

In [59]:
x3 = np.linalg.inv(A) @ b

In [60]:
np.linalg.norm(x2-x3)

3.206162614003982e-14