In [1]:
import numpy as np

# 12. Least Sqaure

### 12.1 Least sqaure problems

In [2]:
A = np.array([[2,0],[-1,1],[0,2]])
b = np.array([1,0,-1])

In [3]:
A.shape

(3, 2)

In [5]:
x_hat = ([1/3, -1/3])

In [8]:
r_hat = A@x_hat - b

In [9]:
np.linalg.norm(r_hat)

0.816496580927726

#### Solutions

In [10]:
np.linalg.inv(A.T@A) @ A.T @ b

array([ 0.33333333, -0.33333333])

In [12]:
np.linalg.pinv(A) @b

array([ 0.33333333, -0.33333333])

### Example

In [13]:
n = 10; # number of lamps
lamps = np.array([ # x, y positions of lamps and height above floor
[4.1 ,20.4, 4],[14.1, 21.3, 3.5],[22.6, 17.1, 6],
[5.5 ,12.3, 4.0],[12.2, 9.7, 4.0],[15.3, 13.8, 6],
[21.3, 10.5, 5.5],[3.9 ,3.3, 5.0],[13.1, 4.3, 5.0],
[20.3, 4.2, 4.5]])
N = 25; # grid size
m = N*N; # number of pixels

In [14]:
# construct m x 2 matrix with coordinates of pixel centers
pixels = np.hstack([np.outer(np.arange(0.5,N,1), np.ones(N)).reshape(m,1),
                   np.outer(np.ones(N), np.arange(0.5,N,1)).reshape(m,1)])

In [21]:
# construct m x 2 matrix with coordinates of pixel centers
pixels = np.hstack([np.outer(np.arange(0.5,N,1), np.ones(N)).reshape(m,1),
np.outer(np.ones(N),np.arange(0.5,N,1)).reshape(m,1)])
# The m x n matrix A maps lamp powers to pixel intensities.
# A[i,j] is inversely proportional to the squared distance of
# lamp j to pixel i.
A = np.zeros((m,n));
for i in range(m):
    for j in range(n):
        A[i,j] = 1.0 / (np.linalg.norm(np.hstack([pixels[i,:], 0])
        - lamps[j,:])**2)
A = (m/np.sum(A)) * A; # scale elements of A

In [22]:
x = np.linalg.solve(A, np.ones(m))

LinAlgError: Last 2 dimensions of the array must be square

In [19]:
A.shape

(625, 10)

In [23]:
m

625

In [28]:
x = np.linalg.pinv(A) @ np.ones(m)

### np.linalg.solve(A,b) 
Computes the “exact” solution, x, of the well-determined, i.e., full rank, linear matrix equation ax = b.

In [44]:
A = [[1,0,0],
    [1,1,1],
    [6,7,0]]
b = [0,24,0]

In [45]:
np.linalg.solve(A,b)

array([ 0., -0., 24.])

In [46]:
np.linalg.pinv(A)@b 

array([1.2377323e-16, 5.6746140e-16, 2.4000000e+01])

In [47]:
np.linalg.inv(A) @ b

array([ 0.,  0., 24.])

### np.linalg.lstsq(A,b) 

Return the least-squares solution to a linear matrix equation.

Solves the equation a x = b by computing a vector x that minimizes the Euclidean 2-norm || b - a x ||^2. The equation may be under-, well-, or over- determined (i.e., the number of linearly independent rows of a can be less than, equal to, or greater than its number of linearly independent columns). If a is square and of full rank, then x (but for round-off error) is the “exact” solution of the equation.

In [49]:
A = np.random.random([3,2])
b = np.random.random([3,1])

In [53]:
x = np.linalg.pinv(A) @ b
x

array([[0.4929695 ],
       [0.13414154]])

In [51]:
A@x-b

array([[-0.2625247 ],
       [-0.09993024],
       [ 0.36205308]])

In [54]:
x, res, rank, s = np.linalg.lstsq(A,b)

C:\Users\Yufei Lin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [57]:
np.linalg.lstsq(A,b)[0]

C:\Users\Yufei Lin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([[0.4929695 ],
       [0.13414154]])